# Generated by Django 2.1.8 on 2020-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('contact_name', models.CharField(max_length=50, null=True, verbose_name='Contact Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=30, null=True, verbose_name='Phone number')),
                ('street_name', models.CharField(max_length=50, null=True, verbose_name='Street name')),
                ('suburb', models.CharField(max_length=50, null=True, unique=True, verbose_name='Suburb')),
                ('postcode', models.CharField(max_length=10, null=True, verbose_name='Postcode')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='State')),
            ],
        ),
    ]
